name: Israel2015
favicon: null
layout_spectrum: 0.6989272104110569
typography_spectrum: 0.46742381481453776
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.4059528736397624
  lightness: 0.9601011576596648
  saturation: 0.9888115578796715
  rhythmicContrast: 0.6109808559995145
purpose: []
